server:
  port: 9994
spring:
  application:
    name: client-service
  banner:
    location: static/banner.txt
  data:
    mongodb:
      host: localhost
      port: 27017
      database: zap-mind
application:
        path: /client-service

auth-service:
  base-url: http://localhost:9992/auth-service

